In [ ]:
#shravya srivastava
#25070123106
#unit 3 data wrangling
#experiment 13
#Aim: To perform preprocessing on a dataset and dealing with missing values

In [2]:
#calling 2 lib
import pandas as pd
import numpy as np
#nan not a number
df1=pd.DataFrame({'C1':[11,21,np.nan],'C2':[15,np.nan,np.nan],
                  'C3':[10,20,30]})
df1

     C1    C2  C3
0  11.0  15.0  10
1  21.0   NaN  20
2   NaN   NaN  30

In [3]:
df1.isna() #where there are missing values we use isna it will say true for missing values in boolean function

      C1     C2     C3
0  False  False  False
1  False   True  False
2   True   True  False

In [4]:
df1.notna() # places with values will show true and missing values will show false

      C1     C2    C3
0   True   True  True
1   True  False  True
2  False  False  True

In [5]:
df1.isna().sum() #counmwise na values how many nun values in each coloumn or axis=0

C1    1
C2    2
C3    0
dtype: int64

In [6]:
df1.isna().sum(axis=1) #row wise na value

0    0
1    1
2    2
dtype: int64

In [7]:
#data cleaning
df1.dropna()#NaN rows are dropped #here axis=1 column and axis=0 row

     C1    C2  C3
0  11.0  15.0  10

In [8]:
df1.dropna(axis=1) #column

   C3
0  10
1  20
2  30

In [9]:
#replacing smth withe default value
df1.fillna(value='DEFAULT')

        C1       C2  C3
0     11.0     15.0  10
1     21.0  DEFAULT  20
2  DEFAULT  DEFAULT  30

In [10]:
df1.fillna(0)

     C1    C2  C3
0  11.0  15.0  10
1  21.0   0.0  20
2   0.0   0.0  30

In [13]:
#replaing missing value with mean mean values if columns are calculates
df1.fillna(df1.mean()) #cant use axis=1

     C1    C2  C3
0  11.0  15.0  10
1  21.0  15.0  20
2  16.0  15.0  30

In [14]:
#preprocessing on a dataset-1
import pandas as pd #debug dataset to give to ml algorith

data = {
    "Roll No": [101, 102, 103, 104, 105],
    "Name": ["Asha", "Rohan", "Meera", "Karan", "Anil"],
    "Age": [20, "-", 21, 20, "22"],
    "Marks": [85, 90, "-", 88, 76],
    "Department": ["CSE", "IT", "CSE", "cse", "E&TC"],
    "Admission_Date": ["01-06-2023", "03-06-2023", "05-06-2023", "07-06-2023", "10/06/23"]
}

df = pd.DataFrame(data)
df
#to use pandas we need tabular form
#data cleaning - NaN in place of missing values here -

   Roll No   Name Age Marks Department Admission_Date
0      101   Asha  20    85        CSE     01-06-2023
1      102  Rohan   -    90         IT     03-06-2023
2      103  Meera  21     -        CSE     05-06-2023
3      104  Karan  20    88        cse     07-06-2023
4      105   Anil  22    76       E&TC       10/06/23

In [20]:
#df.replace("-",np.nan,inplace=True)
#df
#covert columns to numeric ehere meeded
df["Age"]=pd.to_numeric(df["Age"],errors='coerce')
df["Marks"]=pd.to_numeric(df["Marks"],errors='coerce')
df

   Roll No   Name   Age  Marks Department Admission_Date
0      101   Asha  20.0   85.0        CSE     01-06-2023
1      102  Rohan   NaN   90.0         IT     03-06-2023
2      103  Meera  21.0    NaN        CSE     05-06-2023
3      104  Karan  20.0   88.0        cse     07-06-2023
4      105   Anil  22.0   76.0       E&TC       10/06/23

In [22]:
#fill missing age with mean and fill missing marks with median
df["Age"].fillna(df["Age"].mean(),inplace=True)
df["Marks"].fillna(df["Marks"].median(),inplace=True)
df

/tmp/ipykernel_3265/1086756035.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(),inplace=True)
/tmp/ipykernel_3265/1086756035.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Marks"].fillna(df["Marks"].median(),inplace=True)

   Roll No   Name    Age  Marks Department Admission_Date
0      101   Asha  20.00   85.0        CSE     01-06-2023
1      102  Rohan  20.75   90.0         IT     03-06-2023
2      103  Meera  21.00   86.5        CSE     05-06-2023
3      104  Karan  20.00   88.0        cse     07-06-2023
4      105   Anil  22.00   76.0       E&TC       10/06/23

In [23]:
#making all department in capital letters fixing inconsistent text formatiing
df["Department"]=df["Department"].str.upper()#for lower right lower
df

   Roll No   Name    Age  Marks Department Admission_Date
0      101   Asha  20.00   85.0        CSE     01-06-2023
1      102  Rohan  20.75   90.0         IT     03-06-2023
2      103  Meera  21.00   86.5        CSE     05-06-2023
3      104  Karan  20.00   88.0        CSE     07-06-2023
4      105   Anil  22.00   76.0       E&TC       10/06/23

In [31]:
#convert admission date to standard datetime format
df["Admission_Date"]=pd.to_datetime(df["Admission_Date"],format="mixed",dayfirst=True)
df
#NaT-not a time when the date isnt valid ed 32.12.2012
#now data is clean

   Roll No   Name    Age  Marks Department Admission_Date
0      101   Asha  20.00   85.0        CSE     2023-01-06
1      102  Rohan  20.75   90.0         IT     2023-03-06
2      103  Meera  21.00   86.5        CSE     2023-05-06
3      104  Karan  20.00   88.0        CSE     2023-07-06
4      105   Anil  22.00   76.0       E&TC            NaT